# Generated by Django 5.1.3 on 2024-11-15 01:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Tradicional', 'Tradicional'), ('Tradicional Sem Açúcar', 'Tradicional Sem Açúcar'), ('Cenoura com Chocolate', 'Cenoura com Chocolate'), ('Farofa', 'Farofa'), ('Antepasto', 'Antepasto'), ('Brioche', 'Brioche'), ('Browne', 'Browne')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
