# Generated by Django 5.1.3 on 2024-11-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_order_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='batch_id',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
