# Generated by Django 5.1.3 on 2024-11-16 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_order_batch_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='batch_id',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
