# Generated by Django 5.1.3 on 2024-11-17 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_date_of_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='month',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='week',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
