# Generated by Django 5.1.3 on 2024-11-21 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_month_order_week_order_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('week_number', models.PositiveIntegerField()),
                ('month', models.CharField(max_length=20)),
            ],
        ),
    ]
