# Generated by Django 5.1.3 on 2024-11-21 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_week'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='week',
            name='month',
        ),
        migrations.RemoveField(
            model_name='week',
            name='week_number',
        ),
    ]
