# Generated by Django 5.1.3 on 2024-11-21 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_week_month_remove_week_week_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='week',
            name='week_label',
            field=models.CharField(default='tes', max_length=50),
            preserve_default=False,
        ),
    ]
