# Generated by Django 5.1.3 on 2024-11-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_week_week_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='month',
        ),
        migrations.RemoveField(
            model_name='order',
            name='week',
        ),
        migrations.RemoveField(
            model_name='order',
            name='year',
        ),
        migrations.AddField(
            model_name='order',
            name='week_label',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
