# Generated by Django 5.1.3 on 2024-11-28 13:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_order_month_remove_order_week_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Tradicional', 'Tradicional'), ('Tradicional Sem Açúcar', 'Tradicional Sem Açúcar'), ('Cenoura com Chocolate', 'Cenoura com Chocolate'), ('Farofa', 'Farofa'), ('Antepasto', 'Antepasto'), ('Brioche', 'Brioche'), ('Browne', 'Browne')], max_length=50)),
                ('quantity', models.PositiveIntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('week_label', models.CharField(blank=True, max_length=50, null=True)),
                ('date_of_delivery', models.DateField(blank=True, null=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_orders', to=settings.AUTH_USER_MODEL)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
