# Generated by Django 5.1.3 on 2024-11-28 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_pendingorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pendingorder',
            old_name='date_created',
            new_name='date',
        ),
    ]
